# Data Structures

## Hospital
+ name: `渋谷病院` (string) - 病院名
+ phoneNumber: `080-0000-0000` (string) - 電話番号
+ address: `渋谷区○○町00-00` (string) - 住所
+ postalCode: `150-0000` (string) - 郵便番号
+ municipality: `渋谷区` (string) - 市区町村
